// <auto-generated />
using System;
using HBike.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HBikebackend.Migrations
{
    [DbContext(typeof(HBikeContext))]
    [Migration("20230303213759_journey_station")]
    partial class journeystation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.1");

            modelBuilder.Entity("HBike.Models.Journey", b =>
                {
                    b.Property<long>("JourneyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Departure")
                        .HasColumnType("TEXT");

                    b.Property<long>("DepartureStationStationId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Return")
                        .HasColumnType("TEXT");

                    b.Property<long>("ReturnStationStationId")
                        .HasColumnType("INTEGER");

                    b.HasKey("JourneyId");

                    b.HasIndex("DepartureStationStationId");

                    b.HasIndex("ReturnStationStationId");

                    b.ToTable("Journeys");
                });

            modelBuilder.Entity("HBike.Models.Station", b =>
                {
                    b.Property<long>("StationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("StationName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("StationId");

                    b.ToTable("Stations");
                });

            modelBuilder.Entity("HBike.Models.TestItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TestItems");
                });

            modelBuilder.Entity("HBike.Models.Journey", b =>
                {
                    b.HasOne("HBike.Models.Station", "DepartureStation")
                        .WithMany("Departures")
                        .HasForeignKey("DepartureStationStationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HBike.Models.Station", "ReturnStation")
                        .WithMany("Returns")
                        .HasForeignKey("ReturnStationStationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DepartureStation");

                    b.Navigation("ReturnStation");
                });

            modelBuilder.Entity("HBike.Models.Station", b =>
                {
                    b.Navigation("Departures");

                    b.Navigation("Returns");
                });
#pragma warning restore 612, 618
        }
    }
}
